### ISSUE TITLE
Social revoke setup box

### ISSUE THREAD

**Issue by mnsaglam** [KimlikDAO/dapp#4]
In `/al` add a new step (i.e., another box) that comes after `obtain private key`

At the top of the box is a question  "Do you want to set up social recovery to reduce price from $2 to $1?" and an on-off switch.

If the user moves  the switch to `yes` we present several input boxes below the question:

```
|-------------------------------|
|  social revoke addr 1 |   weight |
|-------------------------------|
|  social revoke addr 2 |   weight |
|-------------------------------|
|  social revoke addr 3 |   weight |
|-------------------------------|
                                      | threshold weight |
                                      | total weight|
|----------------------|
| Add more addresses  |
|----------------------|
```

The user enters various addresses and weights. The user also enters a threshold weight, which supposed to represent the weight needed to destroy the issued TCKT.
The UI auto calculates the sum of the weights and warns the user if the sum is less than the threshold (or even if it's too close to it)

By default we show 3 lines. If the user wants to enter more social revoke addresses, clicks on the `add more addresses` button, which adds a few more (maybe just one?) lines.

**Comment by MuhammetCoskun** [comment]
Address validation will be improved.

**Comment by mnsaglam** [comment]
Issue is fixed
