### ISSUE TITLE
TCKT alımında sonra `incele` sayfasına yönlendir

### ISSUE THREAD

**Issue by mnsaglam** [KimlikDAO/dapp#47]
`al` sayfasında başarılı bir TCKT alımının ~1sn süre sonrasında kullanıcıyı `/incele`'ye yönlendir.

Arabirim İngilizce ise, bu sayfanın adı `/view` olarak değişiyor. Arabirim dili şu şekilde tespit edilebilir:

```javascript
const sayfa = dom.TR ? "/incele" : "/view";
```

Başarılı bir TCKT'nin alındığı `promise`, `al` sayfasında `ödeme` altbiriminde.

**Comment by 0x471** [comment]
https://github.com/KimlikDAO/dapp/commit/d2ea976f94b9333d2aaa06ce5baa4cbee8e88d90
