### ISSUE TITLE
Dev sunucusunda sayı'nın "undefined" gözükmesi

### ISSUE THREAD

**Issue by 0x471** [KimlikDAO/dapp#48]
`make dev` komutu ile yerel çalışma ortamında dApp'i çalıştırdıktan sonra `/al` sayfasında "_PDF ile tanıt_" özelliğinde Sayı `undefined` olarak gözüküyor ve işlem yapılamıyor. 

<img width="1440" alt="Screen Shot 2022-09-08 at 17 34 05" src="https://user-images.githubusercontent.com/82776645/189150434-04bc4534-99ee-4312-ac0c-173524a2db40.png">

**Comment by mnsaglam** [comment]
Tamamdır çok teşekkürler. Sanırım Firefox'ta görülebiliyor bu hata. İnceliyorum

**Comment by mnsaglam** [comment]
Yerel sunucuda http scheme'den kaynaklanan bir CORS problemi olduğunu tespit ettik. Yerel sunucuda url'leri `//ipfs.kimlikdao.org` dan `https://ipfs.kimlikdao.org` a geçirmek sorunun çözülmesi için yeterli. Kapatıyorum.
